service: node-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  sls-api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
